### **1. Print "+"**

**Description:**
Given a single positive odd integer 'n' greater than 2, create a NumPy array of size (n x n) with all zeros and ones such that the ones make a shape like '+'. The lines of the plus must be present at the middle row and column.
Hint: Start by creating a (n x n) array with all zeroes using the np.zeros() function and then fill in the ones at the appropriate indices. Use integer division (//) to access the middle rows and columns

**Examples:**
Input 1:
3
Output 1:

```
[[0 1 0]
 [1 1 1]
 [0 1 0]]
```

Input 2:
5
Output 1:

```
[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
```

**Explanation:** Notice that the 1s in the arrays make a shape like '+'.


In [2]:
# Write your code here
import numpy as np

In [11]:
array_size = 7
center = array_size // 2

x = np.zeros((array_size,array_size))

x[center,:] = 1
x[:,center] = 1

In [12]:
x

array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

### **2. Weight Loss**

**Description:** With your 25th birthday fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks starting on a Monday.

```
import numpy as np

weights = 175 - np.arange(5*7)/5
print(weights)
```

Given these daily weights, build an array with your average weight per weekend



In [13]:
# Write your code here
weights = 175 - np.arange(5*7)/5
print(weights)

[175.  174.8 174.6 174.4 174.2 174.  173.8 173.6 173.4 173.2 173.  172.8
 172.6 172.4 172.2 172.  171.8 171.6 171.4 171.2 171.  170.8 170.6 170.4
 170.2 170.  169.8 169.6 169.4 169.2 169.  168.8 168.6 168.4 168.2]


In [24]:
weekend_weight = []
weekend_weight_counter = 0
j = 0

for i in weights:
#     print(f'day {i}')
    weekend_weight_counter += i
    j+=1
    if j == 6:
        weekend_weight.append(weekend_weight_counter/j)
        
        j = 0
        weekend_weight_counter = 0

weekend_weight = np.array(weekend_weight)
print(weekend_weight)

[174.5 173.3 172.1 170.9 169.7]


### **3. Gaming Nicks**

**Description:** You want to start playing a first person shooter game and you are confused to find a gaming nick for yourself, hence you asked your friends and you’ve compiled the names into a Series called nicks.
import numpy as np
import pandas as pd



```
nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')
```

Determine how many people voted for the names ‘Phoenix’, ‘roger’, and ‘Pik’.


In [26]:
# Write your code here
import numpy as np 
import pandas as pd

In [27]:
nicks = pd.Series([
    'Pik', 'Devine99', 'Spawn', 'Prodigy', 'Superkiller420', 'Pik', 'tornado',
    'tornado', 'roger', 'Gabriel', 'Chad', 'Ryan', 'Phoenix', 'Phoenix', 'Phoenix',
    'Phoenix', 'Zeltron', 'Ryan', 'Ruger', 'Ruger', 'roger',
    'roger', 'Chad', 'Chad', 'Gabriel'], dtype='string')

In [30]:
phoenix_counter = 0
roger_counter = 0
pik_counter = 0

for i in nicks:
    if i == 'Phoenix':
        phoenix_counter+=1
    elif i == 'roger':
        roger_counter+=1
    elif i == 'Pik':
        pik_counter+=1
    else:
        continue

print(f'{phoenix_counter} voted for the names Phoenix')
print(f'{roger_counter} voted for the names roger')
print(f'{pik_counter} voted for the names Pik')

4 voted for the names Phoenix
3 voted for the names roger
2 voted for the names Pik
